language: node_js
node_js:
  - "8.9.0"

env:
  - BUILD_PATH="dist"

branches:
  only:
    - master

install:
  - npm install -g @angular/cli

before_script:
  - npm install

script:
  - ng build --prod --base-href ${BASE_HREF} --output-path ${BUILD_PATH}
  - sudo git clone ${CLONE_SOURCE_URL} ${CLONE_TEMP_STORAGE_PATH} --depth=1 --branch=master && sudo rm -rf ${CLONE_TEMP_STORAGE_PATH}/.git
  - sudo cp ${CLONE_TEMP_STORAGE_PATH} ${BUILD_PATH}${CLONE_FINAL_STORAGE_PATH} -r

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  repo: ${GITHUB_DEPLOY_REPO}
  target_branch: master
  local_dir: ${BUILD_PATH}
